### PR TITLE
closes #17 creation of data-raw folder to handle metadata creation

### LINKED ISSUE #17: General Issue: Recreate WHO growth chart data using code
### Background Information

From discussion #13:

```
For WHO, the reference data are at
https://www.who.int/toolkits/child-growth-standards/standards
You want to click on 'standards' and then on 'weight-for-age', length/height for age, BMI-for-age, or weight-for-length/height. And you want to look at the 'Expanded Tables' - this gives the L M S values by day of age.

One question with the WHO charts is whether people want to use weight-for-length or BMI-for age for infants. The official CDC guidance is to use weight-for-length, but this will result in some missing data for kids who have a length outside the range in the WHO data. There's a least 1 paper I know of that concludes that BMI-for-age is better, but I think the 2 metrics are very similar.
```

Recreate the data using `tribble()` for replicability as data source may change overtime and its easier to track than floating csv's
Use snapshots for testthat 

### Definition of Done

See how #15 was done
- [x] Render each necessary WHO dataset as specified above into an .rda object using `tibble::tribble()`
- [ ] Use `testthat::expect_snapshot()` so we can track changes in the feature

### PR DESCRIPTION
**Pull request by Pierre-Wallet**
#17 creation of metadata-creation.R to handle the building of metadatasets, their storage in data folder and their documentation skeleton in R/data.R. #17 creation of 10 metadatasets to reflect WHO website, with their documentation manually updated. #17 creation of snapshot tests for each metadatsets created

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiralpeds (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiralpeds site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the Reference page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by zdz2101 — CHANGES_REQUESTED** [review]
I agree with the intuition to move the script to `data-raw`, can you rename the file to `metadata_creation.R` to `who_metadata_creation.R` and then I'll make the appropriate changes in #16 to mirror what you have done here, so I'll have a `cdc_metadata_creation.R` file. We'll likely merge your PR first, then you can review mine to ensure I did it similarly to you

**Comment by zdz2101** [comment]
from #15 https://github.com/pharmaverse/admiralpeds/pull/16#discussion_r1517893616 we will want to adopt something of this nature

**Comment by Pierre-Wallet** [comment]
@zdz2101 , the update is done. Everything seems clear to me.

**Comment by manciniedoardo** [comment]
FYI that the `data_raw` folder is also being created in [this PR](https://github.com/pharmaverse/admiralpeds/pull/23)

**Comment by zdz2101** [comment]
@Pierre-Wallet can you take a look at: https://github.com/pharmaverse/admiralpeds/pull/16

What we'll do is instead of exporting each dataset, we write them into the `sysdata.rda` file to store them internally, as for what needs to be done here, can you:

1. Modify the `data.R` file and turn it into something like `get_who_data.R` that creates a function called `get_who_data()` that essentially is a wrapped `switch` statement that fetch the respective dataset that the user may need
2. we might have to add a separate script in `data-raw` such that it runs both the `cdc_metadata_creation.R` and `who_metadata_creation.R` and at the bottom has one line that saves all the objects to sysdata
3. modify testthat files to call `get_who_data()` instead of calling the object directly

**Review by zdz2101 — CHANGES_REQUESTED** [review]
@Pierre-Wallet I've decided we should go towards your solution because of the significantly more fragmented nature in the datasets of the WHO data. The 6 datasets for bmi/weight/height for age separated by gender can certainly fit a mold of the `get_()` form factor drafted with gender as an additional argument but and these other 2 weight for height/length charts additionally separated by gender makes its rather confusing too,  I'll make appropriate modifications for the CDC data. 

In terms of house-keeping though, can you separate the `who_metadata_creation.R` into its individual 10 files in the data-raw folder? Each individual dataset can have a corresponding file-to-rda object 

Once this is done, @rossfarrugia if you want to take a look (if it occurs before your time off) feel free to. The `get_xxx_data()` form-factor just doesn't work well with the WHO-data because it's just not as intuitive how the datasets were broken up and it would have a slightly inconsistent look/use compared to the cdc data

**Comment by rossfarrugia** [comment]
No problem @zdz2101 - sounds a good plan, and thanks for @Pierre-Wallet here for thorough review and input to guide us to the ideal strategy. For now please review each others PRs and merge them once ready and when I'm back I'll put a reminder to do some additional checks.

**Comment by Pierre-Wallet** [comment]
> In terms of house-keeping though, can you separate the `who_metadata_creation.R` into its individual 10 files in the data-raw folder? Each individual dataset can have a corresponding file-to-rda object

If I understood correctly, you want 10 .R files, each of them building an .rda object instead of having the building of the ten datasets in one .R file as it currently is?

One question is: do we give up the idea of having all the .rda in one internal rda?

**Comment by zdz2101** [comment]
> > In terms of house-keeping though, can you separate the `who_metadata_creation.R` into its individual 10 files in the data-raw folder? Each individual dataset can have a corresponding file-to-rda object
> 
> If I understood correctly, you want 10 .R files, each of them building an .rda object instead of having the building of the ten datasets in one .R file as it currently is? To be more precise, do you want to :
> 
> 1. keep who_metadata_creation which sources 10 sub programs
> 2. or do you want to have directly 10 programs in data-raw/?
> 
> One question is: do we give up the idea of having all the .rda in one internal .rda?
> 
> * If yes with option 1, we could have it at the end of who_metadata_creation after the 10 subcalls.
> * if yes with option 2, we could have it in a dedicated program
> * if no, well each .rda will be built in each sub program.

Let's go with 1, but change it to a general metadata_creation file, that way it sources 13 sub-programs including the 3 from the CDC, and continue to store it as a one-singular `sysdata.rda` object

**Comment by Pierre-Wallet** [comment]
I will test the options tomorrow.
I think it is possible to get all datasets in one internal .rda and still have a documentation for each dataset.
I keep you posted

**Comment by Pierre-Wallet** [comment]
Hi @zdz2101 ,
I just pushed my updates.
Please have a look to it, I eventually created one pgm for each .rda with its own documentation.
The only issue I have is a lintr one, which does not accept the usage of source().

**Review by zdz2101 — APPROVED** [review]
Looks great @Pierre-Wallet!

**Pull request merged**
